name: 🚀 Run Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  automation-tests:
    runs-on: ubuntu-latest

    services:
      postgres-db:
        image: postgres:latest
        env:
          POSTGRES_USER: delivery_admin
          POSTGRES_PASSWORD: secret_pass
          POSTGRES_DB: food_delivery_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: ☕ Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: 📦 Build package
        run: mvn clean package -DskipTests

      - name: 🚀 Start Spring Boot App in background
        run: java -jar target/food-delivery-app-1.0-SNAPSHOT.jar &

      - name: ⏳ Wait for server to start
        run: sleep 5

      - name: 🧪 Run Unit and API tests via Maven
        run: mvn test -Dtest=!AuthUiTest
