steps:
  # Шаг 1: Скачиваем код
  - name: ⬇️ Checkout code
    uses: actions/checkout@v4

  # Шаг 2: Устанавливаем Java 17
  - name: ☕ Set up JDK 17
    uses: actions/setup-java@v4
    with:
      java-version: '17'
      distribution: 'temurin'
      cache: maven

  # Шаг 3: Собираем проект в готовый JAR-архив
  - name: 📦 Build package
    run: mvn clean package -DskipTests

  # Шаг 4: Запускаем бэкенд на порту 8080 в фоновом режиме Linux (знак & в конце)
  - name: 🚀 Start Spring Boot App in background
    run: java -jar target/food-delivery-app-1.0-SNAPSHOT.jar &

  # Шаг 5: Даем серверу 5 секунд, чтобы он успел полностью проснуться и открыть порт 8080
  - name: ⏳ Wait for server to start
    run: sleep 5

  # Шаг 6: Прогоняем Unit и API автотесты (исключая UI)
  - name: 🧪 Run Unit and API tests via Maven
    run: mvn test -Dtest=!AuthUiTest
